<?php
# ALTERE PARA COLOCAR SEU CONTEUDO PERSONALIZADO
if (!defined('MASCARA')) define("MASCARA", "30");
if (!defined('SINAL')) define("SINAL", "-120..120");
if (!defined('DISABLE')) define("DISABLE", "yes");
if (!defined('DIAS_ATRASO')) define("DIAS_ATRASO", "2");
if (!defined('DNS_SERVER')) define("DNS_SERVER", "8.8.8.8,8.8.4.4");
if (!defined('TCP_MSS')) define("TCP_MSS", "default");
if (!defined('POOL_LOCAL')) define("POOL_LOCAL", "Local-1");
if (!defined('POOL_REMOTO')) define("POOL_REMOTO", "Remoto-1");
if (!defined('ONLY_ONE')) define("ONLY_ONE", "yes");
if (!defined('USE_MPLS')) define("USE_MPLS", "no");
if (!defined('USE_ENCRYPTION')) define("USE_ENCRYPTION", "yes");
