# CONFIGURACOES PARA INCLUDE NO SISTEMA

URL_DOWN="www.mk-auth.com.br"
URL_UP="update.mk-auth.com.br"
PATH_PHP="/opt/mk-auth/hhvm/5-4-45/bin/php"

SYSTEM32_URL_REG="http://$URL_DOWN/update/hotfix32.reg"
SYSTEM32_URL_TAR="http://$URL_DOWN/update/hotfix32.tar.bz2"
SYSTEM32_URL_MD5="http://$URL_DOWN/update/hotfix32.md5"

SYSTEM64_URL_REG="http://$URL_DOWN/update/hotfix64.reg"
SYSTEM64_URL_TAR="http://$URL_DOWN/update/hotfix64.tar.bz2"
SYSTEM64_URL_MD5="http://$URL_DOWN/update/hotfix64.md5"

HOTFIX_URL_REG="http://$URL_UP/hotfix.reg"
HOTFIX_URL_TAR="http://$URL_UP/hotfix.tar.bz2"
HOTFIX_URL_MD5="http://$URL_UP/hotfix.md5"

NOME_FILE_UPD="update22"
