;;;;;;;;;;;;;;;;;;;;;
; Global Options	;
;;;;;;;;;;;;;;;;;;;;;

[global]
pid = /run/php-central.pid
error_log = /var/log/php-central.log
log_level = notice
emergency_restart_threshold = 10
emergency_restart_interval = 1m
process_control_timeout = 10s

;;;;;;;;;;;;;;;;;;;;;
; Pool Definitions	;
;;;;;;;;;;;;;;;;;;;;;

[central]
user = www-data
group = www-data

listen = /run/php-central.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = ondemand
pm.max_children = 50
pm.process_idle_timeout = 10s

security.limit_extensions = .php .hhvm

;;;;;;;;;;;;;;;;;;;;;;
; PHP				 ;
;;;;;;;;;;;;;;;;;;;;;;

php_admin_flag[log_errors] = on
php_flag[display_errors] = off
php_admin_value[error_log] = /opt/mk-auth/log/php-central.log
